<<<<<<< HEAD
name: Publish Eigendata 🐍 distributions 📦 to TestPyPI
=======
name: Publish Pipeline-ai 🐍 distributions 📦 to TestPyPI
>>>>>>> 55fdc07 (eigendata client initial commit)

on:
  push:
    branches:
      - main
jobs:
  build-and-publish:
<<<<<<< HEAD
    name: Build and publish Eigendata 🐍 distributions 📦 to TestPyPI
=======
    name: Build and publish Pipeline-ai 🐍 distributions 📦 to TestPyPI
>>>>>>> 55fdc07 (eigendata client initial commit)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.10
      uses: actions/setup-python@v1
      with:
        python-version: "3.10"
    - name: Install pypa/build
      run: >-
        python -m
        pip install
        build
        --user
    - name: Build a binary wheel and a source tarball
      run: >-
        python -m
        build
        --sdist
        --wheel
        --outdir dist/
        .
    - name: Publish distribution 📦 to Test PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
        verbose: true
